services:
  app:
    image: ginger-cat:latest
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - ginger-cat
  postgres:
    image: 'postgres:15'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      TZ: UTC
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-postgres}'
      POSTGRES_USER: '${DB_USERNAME:-root}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    networks:
      - ginger-cat
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-q',
          '-d',
          '${DB_DATABASE:-postgres}',
          '-U',
          '${DB_USERNAME:-root}',
        ]
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis:/data'
    networks:
      - ginger-cat
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      retries: 3
      timeout: 5s

networks:
  ginger-cat:
    driver: bridge
    name: ginger-cat

volumes:
  postgres:
    driver: local
  redis:
    driver: local